site_name: Pace Link
site_url: https://taixmiguel.github.io/pace-link-wiki/
theme:
  name: material
  language: es

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Español
      lang: es
